### ISSUE TITLE
Create a signal handler

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#100]
Using [SCR](https://github.com/LLNL/scr) or [Sidre](https://github.com/LLNL/axom/tree/develop/src/axom/sidre) or somethine else, we should be able to handle system signals gracefully.

**Comment by joshessman-llnl** [comment]
It doesn't look like either SCR or Axom support signal catching directly, so I think it makes sense to install a simple handler that just calls `exitGracefully` for now - once we have SCR integrated we can also have it checkpoint before terminating.

**Comment by jamiebramwell** [comment]
I poked the radiuss people on slack to see if there are any other tools we should be aware of. I doubt it, but I'll let you know if I hear anything.

**Comment by jamiebramwell** [comment]
From @tgamblin on slack: there is libsigsegv — have you looked at that?  Problem is that it is GPL. https://www.gnu.org/software/libsigsegv/

Alternately you can just use the backtrace that is in glibc: https://stackoverflow.com/questions/77005/how-to-automatically-generate-a-stacktrace-when-my-program-crashes/77336#77336

**Comment by white238** [comment]
https://github.com/LLNL/axom/blob/develop/src/axom/slic/internal/stacktrace.cpp

Axom uses backtrace (and has some windows logic there) to get the stacktraces.

**Comment by joshessman-llnl** [comment]
We could still do `std::signal` with `SIGSEGV` to have slic dump the stack trace before calling `exitGracefully`, though this will obviously cause problems if it's slic or `exitGracefully` that's segfaulting.

**Comment by white238** [comment]
> We could still do `std::signal` with `SIGSEGV` to have slic dump the stack trace before calling `exitGracefully`, though this will obviously cause problems if it's slic or `exitGracefully` that's segfaulting.

Who watches the Watchmen?
