### ISSUE TITLE
Use correct primal values in the sensitivity calls

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#1014]
As written, the sensitivity calculation calls in the `HeatTransfer` and `SolidMechanics` modules will not use the correct primal field values (e.g. temperature) during the backward adjoint pass. See https://github.com/LLNL/serac/blob/a2d7924235565ceccb2a7b341951680aa3afb679/src/serac/physics/heat_transfer.hpp#L921-L927 .

**Comment by btalamini** [comment]
We should check that the correct time is used as well. Ideally, we should write tests that fail before patching the bugs.

**Comment by tupek2** [comment]
Yeah, fixed as far as current testing can confirm.
