### ISSUE TITLE
serac build issues with Docker

### ISSUE THREAD

**Issue by samuelpmishLLNL** [LLNL/serac#1034]
Since I'm unable to successfully build TPLs through uberenv on my mac (see https://github.com/LLNL/serac/issues/1019 and https://github.com/LLNL/serac/issues/1020), today I'm trying to develop using the docker container instead.

After getting it set up, I noticed that configuring CMake takes considerably longer than expected:
~42s in the docker container as opposed to ~2.5s normally. There weren't errors in CMake configuration (initially), but the order of magnitude slowdown is worrying.

After that, building serac fails with error messages:

```
[build] /home/serac/serac/cmake/blt/thirdparty_builtin/googletest/googletest/include/gtest/internal/gtest-port.h:1819: undefined reference to `pthread_getspecific'
[build] /usr/bin/ld: /home/serac/serac/cmake/blt/thirdparty_builtin/googletest/googletest/include/gtest/internal/gtest-port.h:1823: undefined reference to `pthread_key_delete'
[build] /usr/bin/ld: /home/serac/serac/cmake/blt/thirdparty_builtin/googletest/googletest/include/gtest/internal/gtest-port.h:1819: undefined reference to `pthread_getspecific'
[build] /usr/bin/ld: /home/serac/serac/cmake/blt/thirdparty_builtin/googletest/googletest/include/gtest/internal/gtest-port.h:1823: undefined reference to `pthread_key_delete'
[build] /usr/bin/ld: lib/libgtest.a(gtest-all.cc.o): in function `testing::internal::ThreadLocal<std::vector<testing::internal::TraceInfo, std::allocator<testing::internal::TraceInfo> > >::GetOrCreateValue() const':
[build] /home/serac/serac/cmake/blt/thirdparty_builtin/googletest/googletest/include/gtest/internal/gtest-port.h:1857: undefined reference to `pthread_getspecific'
[build] /usr/bin/ld: /home/serac/serac/cmake/blt/thirdparty_builtin/googletest/googletest/include/gtest/internal/gtest-port.h:1864: undefined reference to `pthread_setspecific'
[build] /usr/bin/ld: lib/libgtest.a(gtest-all.cc.o): in function `testing::internal::ThreadLocal<testing::TestPartResultReporterInterface*>::GetOrCreateValue() const':
[build] /home/serac/serac/cmake/blt/thirdparty_builtin/googletest/googletest/include/gtest/internal/gtest-port.h:1857: undefined reference to `pthread_getspecific'
[build] /usr/bin/ld: /home/serac/serac/cmake/blt/thirdparty_builtin/googletest/googletest/include/gtest/internal/gtest-port.h:1864: undefined reference to `pthread_setspecific'
[build] /usr/bin/ld: lib/libgtest.a(gtest-all.cc.o): in function `testing::internal::ThreadLocal<testing::TestPartResultReporterInterface*>::CreateKey()':
[build] /home/serac/serac/cmake/blt/thirdparty_builtin/googletest/googletest/include/gtest/internal/gtest-port.h:1850: undefined reference to `pthread_key_create'
[build] /usr/bin/ld: lib/libgtest.a(gtest-all.cc.o): in function `testing::internal::ThreadLocal<std::vector<testing::internal::TraceInfo, std::allocator<testing::internal::TraceInfo> > >::CreateKey()':
[build] /home/serac/serac/cmake/blt/thirdparty_builtin/googletest/googletest/include/gtest/internal/gtest-port.h:1850: undefined reference to `pthread_key_create'
```

So, something is wrong with the way we're linking against `pthreads`. There are discussions about this on `gtest`, and dedicated options in its CMake build to turn off `pthread` usage. However, setting those flags doesn't work in our build system-- it seems to be conflicting with how BLT is wrapping `gtest`, leading to following error messages when configuring cmake:

```
[cmake] CMake Error at cmake/blt/thirdparty_builtin/googletest/googletest/cmake/internal_utils.cmake:163 (add_library):
[cmake]   Target "gtest_main" links to target "Threads::Threads" but the target was
[cmake]   not found.  Perhaps a find_package() call is missing for an IMPORTED
[cmake]   target, or an ALIAS target is missing?
[cmake] Call Stack (most recent call first):
[cmake]   cmake/blt/thirdparty_builtin/googletest/googletest/cmake/internal_utils.cmake:217 (cxx_library_with_type)
[cmake]   cmake/blt/thirdparty_builtin/googletest/googletest/CMakeLists.txt:143 (cxx_library)
```

However, bringing in `gtest` through `FetchContent` (the way [they recommend](https://google.github.io/googletest/quickstart-cmake.html#set-up-a-project)) leads to no pthread linkage errors or configuration problems:

```
include(FetchContent)
FetchContent_Declare(
  googletest
  URL https://github.com/google/googletest/archive/5376968f6948923e2411081fd9372e71a59d8e77.zip
)
set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)
FetchContent_MakeAvailable(googletest)

add_executable(example example.cpp)
target_link_libraries(example gtest_main)
```

-------------

Does serac need to get `gtest` through BLT for some reason, or can we just get it using `FetchContent` to avoid this sort of issue?

**Comment by white238** [comment]
Try setting this CMake variable, `gtest_disable_pthreads`, to `ON` either in the host-config or the cmake command line.

**Comment by white238** [comment]
The GoogleTest that is in BLT has been vetted and slightly altered (though minorly at this point) to support the customers and platforms on LC.

**Comment by samuelpmishLLNL** [comment]
> Try setting this CMake variable, gtest_disable_pthreads, to ON either in the host-config or the cmake command line.

That's what I did, and it resulted in the configuration error message I described above:

```
[cmake] CMake Error at cmake/blt/thirdparty_builtin/googletest/googletest/cmake/internal_utils.cmake:163 (add_library):
[cmake]   Target "gtest_main" links to target "Threads::Threads" but the target was
[cmake]   not found.  Perhaps a find_package() call is missing for an IMPORTED
[cmake]   target, or an ALIAS target is missing?
[cmake] Call Stack (most recent call first):
[cmake]   cmake/blt/thirdparty_builtin/googletest/googletest/cmake/internal_utils.cmake:217 (cxx_library_with_type)
[cmake]   cmake/blt/thirdparty_builtin/googletest/googletest/CMakeLists.txt:143 (cxx_library)
```

**Comment by white238** [comment]
There are several places where `Threads::Threads` should have been created, `conduit` does it, here (https://github.com/LLNL/blt/blob/29eecef7652728ec37d9fe0b7d7f41e3184ac7eb/thirdparty_builtin/CMakeLists.txt#L90-L93).  I am not sure why you aren't getting one of them.


Can you try just adding:

```
find_package( Threads )
```

somewhere in the CMakeLists.txt. It shouldn't matter where. This is an issue that creeps up a lot. We should probably add finding it by default or add it to BLT when `ENABLE_GTEST` is on.

**Comment by white238** [comment]
Closed due to fixing @samuelpmishLLNL build locally. We can reopen if we run into this again.
