### ISSUE TITLE
Add methods to erase time history for design optimization of transient physics

### ISSUE THREAD

**Issue by kswartz92** [LLNL/serac#1051]
There are containers in the base physics class, e.g. time steps and checkpointed states, that need to be emptied in between design iterations. In the smith meeting on 12/14/23 possible solutions were discussed including adding reset methods for each individual entity that needs to be cleared, or added a "global" reset method that would return the base physics class to the "state" the module is in immediately following construction.

**Comment by btalamini** [comment]
Closed by #1183
