### ISSUE TITLE
Caliper macros doubly defined

### ISSUE THREAD

**Issue by btalamini** [LLNL/serac#1164]
We now define a bunch of no-op Caliper macros when Serac is built without Caliper. It seems like LiDO does the same thing, and so when LiDO is built in codevelop mode, the compilation fails because the macros are doubly defined. Not sure if this is properly a Serac issue or a Caliper issue. I kindly request advice from @white238 or @chapman39 .

**Comment by chapman39** [comment]
It might be somewhat ugly but we could check if each macro is defined before setting it. I'm not sure of another solution. I can create a quick PR for this.
