### ISSUE TITLE
Consider refactoring to comply with ISOCPP core guidelines

### ISSUE THREAD

**Issue by joshessman-llnl** [LLNL/serac#118]
There are couple maintainability improvements that have caught my eye and could be refactored - I've linked relevant sections of the ISOCPP guidelines:

1. The [two-phase initialization](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rnr-two-phase-init) for the solvers (constructor + `completeSetup`) - instead, a combination of reasonable defaults and constructor arguments (e.g. a class representing/encapsulating BCs) could be used to ensure that the solvers are always in a valid (solvable) state.
2. Switch to [`class`es and constructors](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-struct) for `BoundaryCondition` and `FiniteElementState` types - these have invariants, e.g. the FES should be constructed with the mesh, the GF should be constructed with the FES, etc
3. Separate [interface/behavior from state/implementation](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Ri-abstract) in `BaseSolver` - potentially there could be a separate helper class responsible for any common helper methods, in which case `BaseSolver` only determines the functions that a solver must implement (e.g. `advanceTimestep`)
4. There's still work to be done with regard to [function/constructor parameters and ownership](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#S-functions) as well.

Some of these improvements may be mutually inclusive with a switch to a boundary condition manager.

**Comment by samuelpmishLLNL** [comment]
I agree with 1. We have no real way to enforce that the user has properly initialized a solver before calling `completeSetup()`. It would be much nicer to be able to tell a user at compile time that they have not properly initialized a solver object, but I'm not sure which approach to take to achieve this.

I'm not sure exactly what you mean with 4., but I think our plan for function parameters was to use raw pointers for non-owning refererences,  `std::shared_ptr` for references to objects the user might wish to change/refer to after calling `completeSetup()` and `std::unique_ptr` when passing ownership.

**Comment by joshessman-llnl** [comment]
With regard to 4, I just meant that I think there are deviations from the ownership rules you mentioned.

**Comment by joshessman-llnl** [comment]
>  It would be much nicer to be able to tell a user at compile time that they have not properly initialized a solver object

C++ doesn't provide any way of checking the order in which functions are called at compile time, though you could always have a `bool setup_completed_;` member to at least make sure that `completeSetup` has been called before running `advanceTimestep`.

Instead, you could modify the class such that it's impossible to have a solver in an invalid state, maybe something like:
```cpp

BoundaryConditionManager bcs(mesh);
bcs.addEssential(disp_attrs, disp_coef);
bcs.addNatural(trac_attrs, trac_coef);

HyperElasticMaterial material(lambda, mu);

Solver lin_solver(lin_params);

NonlinearSolidSolver solid_solver(mesh, bcs, material, lin_solver);
```
in which case you'd have a solver object that's "ready to go".  It gets kind of messy to have greater than like four function arguments, so there may also be value in abstracting out the idea of a "problem" (mesh + BCs + material) and the methods used to solve it.

**Comment by jamiebramwell** [comment]
There are two reasons I used the "two phase initialization" anti-pattern:

1) I wanted to avoid a constructor with a ton of arguments
2) I can imagine a user changing parameters as the solver evolves over time (e.g. adding or deleting a boundary conditions)

I think both of these are solved by breaking each solver into subcomponents like `
NonlinearSolidSolver solid_solver(mesh, bcs, material, lin_solver);` Maybe each solver should have a corresponding `params` and `material` class? This is similar to what @samuelpmish was thinking about for complex materials if I recall correctly.

**Comment by jamiebramwell** [comment]
Items 2-4 are clearly better than what is there currently and I wholly support them.

**Comment by joshessman-llnl** [comment]
I think that as long as the need for time-evolving BCs is taken into account when this hypothetical `BoundaryConditionManager` is implemented (e.g. shared object between user code and solver), encapsulating BCs within their own class shouldn't be a problem.
