### ISSUE TITLE
Adding time dependency to essential BC breaks dynamic solid adjoint test

### ISSUE THREAD

**Issue by kswartz92** [LLNL/serac#1191]
@tupek2 I located a very small change (adding time to essential bc) that breaks the sensitivity test, here is a branch with the change https://github.com/LLNL/serac/tree/swartz10/transientEssentialBCtest

**Comment by kswartz92** [comment]
I was looking through the physics modules and noticed that `ode_time_point_` isn't updated in `reverseAdjointTimestep()`. The check-pointed time steps and states are grabbed, but the absolute time doesn't seem to be decreasing during the reverse pass. Could this be the issue?

**Comment by tupek2** [comment]
I have a branch that addresses all of this.  I need to run your problem to make sure the dirichlet time dependence works now.

**Comment by btalamini** [comment]
Fixed by #1183

**Comment by btalamini** [comment]
Fixed by #1183
