### ISSUE TITLE
save clang-format git patch as artifact on failure

### ISSUE THREAD

**Issue by samuelpmishLLNL** [LLNL/serac#1208]
Right now, if the CI job for checking style fails, it dumps text to the log that can be made into a patch. However, that text is interleaved with some other console output, and seemingly prefixed by timestamps, which means it takes manual effort to produce the actual patch file that can be `git apply`-ed. On my machine/browser, the Azure devops UI doesn't play nicely with text selections (e.g. vertically scrolling the log changes the selected text) which makes it annoying to successfully select the relevant patch info.

It would be more ergonomic if instead, on a style failure the patch information would be written to a file that gets uploaded as an artifact. That way, the user only has to click a button to download the file and we're sure that no clerical errors were made when manually creating the patch.

**Comment by white238** [comment]
You can comment on the PR "/style" now and it will style your code and apply it to your branch.

**Comment by samuelpmish** [comment]
oh, I wasn't aware of that change. Is it documented somewhere?
