### ISSUE TITLE
Questions about requiring currently optional packages (petsc, tribol, sundials) and testing them in CI

### ISSUE THREAD

**Issue by chapman39** [LLNL/serac#1221]
This issue is a discussion place about optional packages (tribol, sundials, petsc, etc.).

* Should we require Tribol? PETSc? Sundials?
* Which optional packages should we test in CI?
* Ideally we should test all combinations of optional packages enabled/ disabled, but this isn't feasible.
* Requiring some more packages will reduce the amount of CI jobs required, since we won't have as many combination of options to cover.

Right now, we do not test the no-petsc case in CI, which lead to this issue for example https://github.com/LLNL/serac/pull/1217.

**Comment by tupek2** [comment]
My vote: have a no-tribol build.  Have a no_petsc and no_sundials build (together) there are sort of our TPL solvers, so its OK to test that things work when we have neither and that everything else also works when we have both.
