### ISSUE TITLE
Enable/fix `default.lua` test cases

### ISSUE THREAD

**Issue by white238** [LLNL/serac#1250]
These were turned off when we were fixing the input file functionality but can/should be turned back on.

https://github.com/LLNL/serac/blob/6357a07c8caad21f85ec0a54f21ecb1aeb863f45/src/drivers/CMakeLists.txt#L17-L32

The input file also seems to be fundamentally broken with this error (or the error is wrong):

```
[ERROR (/serac/src/drivers/serac.cpp:223)]
Solid order '1' and thermal order '2'' do not match.
** StackTrace of 5 frames **
Frame 1: axom::slic::logErrorMessage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)
Frame 2: getOrder(std::optional<serac::SolidMechanicsInputOptions>, std::optional<serac::HeatTransferInputOptions>, std::optional<serac::ThermomechanicsInputOptions>)
Frame 3: main
Frame 4: __libc_start_main
Frame 5: _start
=====

```

Also the integration tests have a file globbing problem that needs to be solved to re-enable them (thanks @chapman39 for locating this):

https://github.com/LLNL/serac_tests/blob/662c093dddcff184983547ea0212adce3632a751/integration/test.ats#L231

**Comment by chapman39** [comment]
The solid ordering is an issue that arose after updating the input files to handle functional. I remember discussing this with @jamiebramwell but don't remember exactly what the error is about.

In any case, I think it's best to either completely remove the default lua or replace its contents with another currently existing (and working) lua file.
