### ISSUE TITLE
Some factory methods for `Domain' don't fully construct valid objects

### ISSUE THREAD

**Issue by btalamini** [LLNL/serac#1272]
The Boolean set operation methods that construct instances of `Domain` don't fill out all the member variables. The missing ones (the `mfem_*_ids_`) are needed for getting indices into `FiniteElementState` instances.

This bug is also present in the `EntireDomain` and `EntireBoundary` methods, but I'm about to submit a simple fix for those.

**Comment by samuelpmishLLNL** [comment]
I could fix this in its own PR or roll it into the DG one (which is already making some improvements to the Domain class)-- do you have any preference?
