### ISSUE TITLE
Add dummy GPU build

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#137]
Add a GPU-enabled build to the gitlab CI to test the advanced architecture compilers for our use of new language features.

**Comment by white238** [comment]
We should use a compiler spec that Axom already supports or start with theirs and update the compilers.  Here is a good start:

https://github.com/LLNL/axom/blob/5d7d60ec4f7c0a48bb8923cdfc1e32d9bac460c9/scripts/uberenv/spack_configs/blueos_3_ppc64le_ib_p9/compilers.yaml#L28
