### ISSUE TITLE
Investigate CI for OSX builds

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#179]
As we have users that use and OSX environment, we should find a testing framework to harden the spack-configs for this setup.

**Comment by joshessman-llnl** [comment]
I started a branch (https://github.com/LLNL/serac/tree/ci/essman/osx_build) to attempt to implement this on the Mac OSX images provided by Azure CI but spack is broken on these images:
per
https://github.com/spack/spack/issues/14102
with open PR 
https://github.com/spack/spack/pull/18205
