### ISSUE TITLE
Investigate LaTeX in readthedocs

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#180]
We should see if it's possible to integrate LaTeX in readthedocs/sphinx. @samuelpmishLLNL has some theory documentation that would use this.

**Comment by joshessman-llnl** [comment]
LaTeX is supported natively in Restructured Text:

I added some text to one of our Sphinx pages
```rst
.. math::

   e^{i\pi} + 1 = 0
```
...and confirmed that it rendered:
![image](https://user-images.githubusercontent.com/68349992/92613609-c3a00000-f280-11ea-9a02-4e1b6ce00384.png)

**Comment by jamiebramwell** [comment]
Thanks for checking!
