### ISSUE TITLE
Allow custom MFEM solvers

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#186]
We should add hooks for user-specific custom linear solvers and preconditioners, e.g. set by a generic `mfem::solver` object.

**Comment by joshessman-llnl** [comment]
Were you thinking that this would be added to the physics module API, e.g.,
`void NonlinearSolidSolver::setLinearSolver(unique_ptr<mfem::Solver>&&);`?

**Comment by jamiebramwell** [comment]
I think cleaning up the coefficient interface (https://github.com/LLNL/serac/issues/192) is probably higher priority though.
