### ISSUE TITLE
Having a cuda/noncuda tpl spec causes overwrite of spack install dir

### ISSUE THREAD

**Issue by white238** [LLNL/serac#191]
I'm not sure we care enough to fix this... but if you have two specs like the following:

"clang@ibm_gfortran+devtools+cuda"
"clang@ibm_gfortran+devtools+cuda cuda_arch=70"

They will build to the same Spack build directory:

/common/build/path/clang@ibm_gfortran

**Comment by jamiebramwell** [comment]
Eh, I think this is fine.
