### ISSUE TITLE
Add Pastix and Strumpack as solver options

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#206]
As an alternative to DSuperLU, we should investigate Strumpack and Pastix as a parallel sparse direct solver option. While an MFEM strumpack interface exists, the Pastix option would need to be added.

**Comment by joshessman-llnl** [comment]
Were you thinking that these would be optional in Serac (e.g. via `+strumpack` `+pastix` variants)?

**Comment by jamiebramwell** [comment]
If one of them is more reliable than dsuperlu, I say making that one required and leaving dsuperlu as optional is the way to go. Essentially, I want one direct solver option to be a required dependency. The MDG folks (@solberg2 and Mike) say that pastix is the better choice (and I would agree with that), but strumpack is available in MFEM now.

**Comment by solberg2** [comment]
We have no experience with strumpack.  I will have to look it up.

**Comment by joshessman-llnl** [comment]
STRUMPACK may require some work:

https://github.com/spack/spack/blob/6b70597271232e442b9e729b45adaee02bccf8c0/var/spack/repos/builtin/packages/mfem/package.py#L223-L224

```
    # The STRUMPACK v3 interface in MFEM seems to be broken as of MFEM v4.1
    # when using hypre version >= 2.16.0:
```
