### ISSUE TITLE
Index the state vector bundle by name

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#22]
For clarity for the user, I think the [`m_state`](https://github.com/LLNL/serac/blob/5db79168d80c487ed7280b569fdcabd18fffb77e/src/solvers/base_solver.hpp#L18) variable should be a `std::map` or something like it.

**Comment by samuelpmishLLNL** [comment]
I'm making this change too, along with the raw pointer stuff

**Comment by jamiebramwell** [comment]
This was resolved by using references in the derived solver classes.
