### ISSUE TITLE
Organize the unit tests

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#222]
At some point we should revisit the unit tests.  either move them into a test directory next to their source they go with or rename and put them in subdirectories so they more match the src dir.

_Originally posted by @white238 in https://github.com/LLNL/serac/pull/221#issuecomment-699121003_

**Comment by white238** [comment]
Though maybe ignore this until inlet is done and we can move some of them out of there an into the integration tests.

**Comment by white238** [comment]
Outside LLNL test suites from @adrienbernede :

https://github.com/hpc/pavilion2
https://jchronoss.hpcframework.com/
https://github.com/cea-hpc/PCVS
