### ISSUE TITLE
Move away from mfem::Array types

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#23]
When possible, I think it would be best to go to `std::Vector` or `std::map` instead of `mfem::Array` types. This reduces the dependency on MFEM from a user perspective.

**Comment by samuelpmishLLNL** [comment]
I just ran a small test where mfem::Array< FiniteElementState > (with std::shared_ptr) segfaults on deconstruction, but std::{map, vector}< FiniteElementState > containers don't. I don't know what the difference in implementation is, but it is a little bit concerning.

**Comment by jamiebramwell** [comment]
I looks like it's using the fairly new memory manager classes [here](https://github.com/mfem/mfem/blob/v4.0/general/array.hpp), so I say we move to std::map/vector until we have a good reason not to.

**Comment by samuelpmishLLNL** [comment]
A downside of the `std::map` for `m_state`: making an innocent typo in one of the field names will compile but result in potentially cryptic runtime errors. I wrote "displacment" instead of "displacement" initially, and it took me longer than I'd like to admit to understand what was going wrong.

**Comment by white238** [comment]
Realize this is coming from a purely CS person. Do these have to be in the same data structure? It seems like an individual array that is named for each would be better. Or an array that holds a struct for each one.

**Comment by jamiebramwell** [comment]
Yeah, I'm not sure what is the best. To have a common interface for each solver, we need to have some interface in the `BaseSolver` class which can lookup state information where each solver could have a different number of state variables. For example, the thermal solver only has a temperature field but the solid solver has displacement and velocity fields. Any thoughts?

**Comment by jonwong12** [comment]
I think it depends on how you plan to arrange the solvers. One thing you could do is for solvers that are dependent on one another you could set the references to the gridfunctions from whatever code is organizing the coordinate flow of the solvers. Then you won't have to do any weird look-ups.

For the state, if you want strings, doesn't it make more sense to use std::unordered_map since there isn't really an order associated?

**Comment by jamiebramwell** [comment]
I think there are two use casese we have to consider. The first is a simple proxy app type person who doesn't want to see any of the memory management guts. The second is a large integrated code that has their own data structures and memory managers. I'm not really sure what the best answer is, so we should probably have a WebEx to discuss this.

**Comment by jamiebramwell** [comment]
I think this will be resolved by using a real data store as we discussed in the referenced webex.
