### ISSUE TITLE
Investigate why using-with-cmake example fails

### ISSUE THREAD

**Issue by white238** [LLNL/serac#230]
The `build_src.py` and `build_tpls.py` scripts fails on the last step when it runs `serac_example`.  It only fails when you run all compiler specs and specifically the gcc@8.3.1 fails everytime.  Running the script with just the gcc@8.3.1 succeeds and running the test manually afterwards succeeds.

I've currently tried:

* `sleep 60` prior to running test
* `ls -al` to make sure its exectuable
* embedding test inside of ctest

```
Scanning dependencies of target serac_example
[ 50%] Building CXX object CMakeFiles/serac_example.dir/serac_example.cpp.o
[100%] Linking CXX executable serac_example
[100%] Built target serac_example
total 3560
drwx--S--- 3 white238 smithdev    4096 Oct  2 18:50 .
drwx--S--- 3 white238 smithdev    4096 Oct  2 18:50 ..
-rw------- 1 white238 smithdev   16854 Oct  2 18:50 CMakeCache.txt
drwx--S--- 6 white238 smithdev    4096 Oct  2 18:50 CMakeFiles
-rw------- 1 white238 smithdev    1227 Oct  2 18:50 CTestTestfile.cmake
-rw------- 1 white238 smithdev    6173 Oct  2 18:50 Makefile
-rw------- 1 white238 smithdev    1790 Oct  2 18:50 cmake_install.cmake
-rw------- 1 white238 smithdev    2106 Oct  2 18:50 compile_commands.json
-rwx------ 1 white238 smithdev 3573824 Oct  2 18:50 serac_example
Running tests...
Test project /usr/WS2/smithdev/libs/toss_3_x86_64_ib/2020_10_02_18_02_26/_serac_build_and_test_2020_10_02_18_02_26/install-quartz-toss_3_x86_64_ib-gcc@8.3.1/e
xamples/using-with-cmake/build
    Start 1: serac_example
1/1 Test #1: serac_example ....................SIGPIPE***Exception:   0.12 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.16 sec

The following tests FAILED:
	  1 - serac_example (SIGPIPE)
Errors while running CTest
make: *** [test] Error 8
```

**Comment by white238** [comment]
More info... it's always the host-configs after the first one that fails.  So if you have 3 host-configs the last two fail.

**Comment by white238** [comment]
succeeds when inside an allocation (`salloc` -> `build_src`) but not when you run with `srun -N1 build_src`.

**Comment by adrienbernede** [comment]
Potential hint (no guarantee!): Some form of pipe buffer filling?

> Warning Use communicate() rather than .stdin.write, .stdout.read or .stderr.read to avoid deadlocks due to any of the other OS pipe buffers filling up and blocking the child process.

https://docs.python.org/3/library/subprocess.html

**Comment by adrienbernede** [comment]
More here:
https://docs.python.org/2/library/subprocess.html#subprocess.Popen.wait

**Comment by white238** [comment]
So this doesn't get lost again, from @joshessman-llnl 👍 

```
write(13, "cmd=init pmi_version=2 pmi_subversion=0\n", 40) = -1 EPIPE (Broken pipe)
```

**Comment by white238** [comment]
Turns out I don't know all the rules of srun'ing.  The problem was we were calling two executables that called `MPI_Init` in the same `srun`.  Even though there was an `MPI_Finalize` between them, it causes the broken pipe.

Basically, this command `srun -n1 ./run.sh`, where `run.sh` is:

```
#!/bin/bash

./myexec
./myexec
``` 

this is the proper way to do it:
```
#!/bin/bash

srun -n1 ./myexec
srun -n1 ./myexec
``` 

Though this depends on how the machine is scheduled.
