### ISSUE TITLE
Move to MFEM 4.1

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#24]
Upgrade the MFEM dependency to the newly released [v4.1](https://github.com/mfem/mfem/tree/v4.1). This should happen sooner rather than later as it greatly improves GPU support.

**Comment by adrienbernede** [comment]
I would like serac CI to be working again at first. My PR with Uberenv is a bit different.

Currently I’m having issues with Uberenv in Serac, with an Hypre include file missing either at MFEM or Serac build/link time.

I have other things on my plate, but I would like to solve this in the following days. It should then help moving to mfem 4.1.

**Comment by jamiebramwell** [comment]
No rush! When I say "sooner rather than later" I meant sometime before fall instead of sometime this week. Thanks again for all of the help!

**Comment by adrienbernede** [comment]
Fixed by #66
