### ISSUE TITLE
Add NAFEMS benchmarks

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#250]
We should add the [NAFEMS benchmarks](https://www.nafems.org/publications/resource_center/p18/) as validation tests. This might need to wait until we have an integration test framework.

**Comment by samuelpmishLLNL** [comment]
Is this not something we're not interested in any more?

**Comment by jamiebramwell** [comment]
It is, but I was planning on breaking this into smaller chunks.

**Comment by samuelpmishLLNL** [comment]
> It is, but I was planning on breaking this into smaller chunks.

👍
