### ISSUE TITLE
Settle on casing across project for filenames, variables, and classes

### ISSUE THREAD

**Issue by white238** [LLNL/serac#28]
This should be discussed as a group or just go with something.

I don't care either way, I just want it to be consistent.

Pot Hole Case? Camel Case?

**Comment by samuelpmish** [comment]
My vote is for adopting [google's c++ style guide](https://google.github.io/styleguide/cppguide.html). It's pretty thorough, and has [good tooling](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) to automatically apply formatting rules.

For filenames, their convention is `lower_with_underscores.h`, which is consistent with STL files (e.g. `#include <unordered_map>`).
