### ISSUE TITLE
Add Spack variants for optional packages

### ISSUE THREAD

**Issue by white238** [LLNL/serac#327]
For example, Sundials could be optional but this requires the new clingo Spack concretizer to work around the bugs in the current Spack concretizer.

**Comment by joshessman-llnl** [comment]
This is implemented in https://github.com/LLNL/serac/tree/feature/essman/shared_build

We should be able to move forward with the Clingo concretizer once https://github.com/spack/spack/pull/20657, https://github.com/spack/spack/issues/20736, and https://github.com/spack/spack/issues/20580 are resolved.
