### ISSUE TITLE
Investigate methods for mfem and axom co-development

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#340]
We should look at using an mfem submodule (without the cmake add_subdirectory!) or the spack dev environment for co-development of mfem inline with Serac. This should be optional so users don't have to worry about this process.

**Comment by jamiebramwell** [comment]
This came up again so it should get bumped to the top of the priority list.

**Comment by joshessman-llnl** [comment]
Exploring MFEM as a submodule identified an issue that will be fixed by https://github.com/mfem/mfem/pull/1986
