### ISSUE TITLE
Add convenience constructors for mfem::DenseMatrix and mfem::Vector objects

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#346]
it might be worth making a PR to mfem to add some convenience constructors of the form:

```cpp
template < int m, int n >
DenseMatrix(const double (&values)[m][n]) { ... }

template < int n >
Vector(const double (&values)[n]) { ... }
```

so we can just write `mfem::DenseMatrix M = {{2.0, 1.0, 0.0}, {1.0, 4.0, 1.0}, {0.0, 1.0, 2.0}}` and avoid having to use the lambda workaround

_Originally posted by @samuelpmish in https://github.com/LLNL/serac/pull/335#discussion_r564012332_

**Comment by joshessman-llnl** [comment]
This was a good idea - addressed by https://github.com/mfem/mfem/pull/2034

**Comment by jamiebramwell** [comment]
Thanks for putting this together!
