### ISSUE TITLE
Double call to uberenv causes incoherency in the logs of Gitlab CI.

### ISSUE THREAD

**Issue by adrienbernede** [LLNL/serac#350]
See https://lc.llnl.gov/gitlab/smith/serac/-/jobs/161492/raw

**Comment by white238** [comment]
Are you talking about printing out the spec? uberenv has always done that.  If you scroll down its using clang to do the actual compiles.

**Comment by adrienbernede** [comment]
... but why? Why "_uberenv_ has always done that"?

**Comment by adrienbernede** [comment]
All that time using Uberenv and I wouldn't have noticed... ?

**Comment by white238** [comment]
Dunno. it should be fixed but it just does? =)

**Comment by adrienbernede** [comment]
Closing since the build indeed uses Clang.

**Comment by adrienbernede** [comment]
@white238 I think I found something:
There are in facts 2 calls to uberenv in the build script, on with --create-mirror, but an empty spec, and then a second one with the spec. For some reason (nested processes?) the second call does not print the spec.
So this is not uberenv, it's the serac build script.

**Comment by white238** [comment]
ah yea... we could add that to the build_tpls.py script.  That explains why i always see it and you didnt. I rarely call uberenv directly.

I take the deserved cone of shame.....

**Comment by adrienbernede** [comment]
not shame, responsibility maybe ;)
