### ISSUE TITLE
Add sundials monitoring build flag

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#355]
From @jandrej in the Teams chat: 

Can I request a small change in the Sundials TPL? We should enable (the recently changed) build system flag SUNDIALS_BUILD_WITH_MONITORING to allow printing in linear iterations in KINSOL. If someone with the machinery for it could rebuild tpls that would be greatly appreciated

**Comment by white238** [comment]
Should this always be on for Serac only? Is this a one off thing?  or should we be adding a variant to the Sundials package and pushing that up to spack's main repo then utilizing that variant on all our builds?

**Comment by jandrej** [comment]
It should be enabled in Serac always. Putting it upstream with the spack package is a good idea but not necessary.
