### ISSUE TITLE
Use `output_type` properly

### ISSUE THREAD

**Issue by white238** [LLNL/serac#362]
I was looking into if we required a specific capitalization for the `output_type` input variable and it turns out we are just hard coding the output_type to visit.  We should fix that and also lower case the string before converting to the enum.

https://github.com/LLNL/serac/blob/bd957565001c35e8bece9c8bc2958e049f803be5/src/drivers/serac.cpp#L118

**Comment by joshessman-llnl** [comment]
Right now the conversion logic is just part of the test schema:
https://github.com/LLNL/serac/blob/0e62839e258a738e0f74b84524990bfeb981640e/tests/test_utilities.cpp#L33-L35
https://github.com/LLNL/serac/blob/0e62839e258a738e0f74b84524990bfeb981640e/tests/test_utilities.cpp#L182-L191

but I think this can be moved to `input.cpp`.
