### ISSUE TITLE
Add developer mode to turn off warning build failures

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#366]
We should have a dev mode in our build system to turn off extra warnings or possibly build failure on warning.

**Comment by joshessman-llnl** [comment]
I think it's reasonable to add an option to just disable `-Werror` but still display all the warnings that would cause failures in CI so developers aren't "surprised" by CI failures

**Comment by joshessman-llnl** [comment]
It looks like this is possible already with `-DENABLE_WARNINGS_AS_ERRORS=OFF`. I'll add this to the docs.
