### ISSUE TITLE
Clean up the coefficient definitions

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#388]
It would be nice to define coefficients like this:

```lua
initial_displacement = {x = 0.0, y = 0.0, z = 0.0}
initial_velocity = function (v) return Vector.new(0, 0.5*v.x) end
```

(@samuelpmishLLNL , please correct me if you are thinking of something else.)

**Comment by jonwong12** [comment]
@jamiebramwell For the `initial_velocity` case, I think it gets tricky if you change the size of the vector in the function. Otherwise, you'd need some way to accommodate different vector sizes.
