### ISSUE TITLE
Thermal-only input files don't work

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#401]
Due to issues with inlet verifiers, thermal-only input files currently do not work.

**Comment by joshessman-llnl** [comment]
It looks like this will be fixed by https://github.com/LLNL/axom/pull/481

**Comment by jamiebramwell** [comment]
Yeah, I looked into fixing this, and decided it was worth it to just wait for this to come down the pipe and do it right.

**Comment by joshessman-llnl** [comment]
Tested + confirmed to work with:

- [x] https://github.com/LLNL/axom/pull/495
