### ISSUE TITLE
Problem with building serac

### ISSUE THREAD

**Issue by samanseifi** [LLNL/serac#44]
I'm trying to build serac on my computer. I get the following Checksum error both in building developer's tools and dependencies.

`Error: ChecksumError: sha256 checksum failed for /home/saman/serac/uberenv_libs/builds/spack-stage-rz4d952n/4075.patch`

and follows by
```
    Expected 3387faf4a71efe81c0fa17410b270ca7d352081ac88d2322df3da9bb6a6a3f2d but got 42d8b2163a2f37a745800ec13a96c08a3a20d5e67af51031e51f63313d0dedd1

/home/saman/serac/uberenv_libs/spack/lib/spack/spack/package.py:1088, in do_fetch:
       1085
       1086        self.stage.cache_local()
       1087
  >>   1088        for patch in self.spec.patches:
       1089            patch.fetch(self.stage)
       1090            if patch.cache():
       1091                patch.cache().cache_local()
```
anyone knows how to resolve this? Thanks.

**Comment by samuelpmish** [comment]
Hi, this is likely related to serac currently using an old version of spack. Can you try replacing the project.json file from the one in the bump_spack_version branch and see if that helps?

https://github.com/LLNL/serac/blob/bump_spack_version/scripts/uberenv/project.json

**Comment by adrienbernede** [comment]
Hello @samanseifi, could you tell us on what system you are trying to install?

**Comment by samanseifi** [comment]
Thanks @samuelpmish , I'll try that and I'll let you know.

Hello @adrienbernede. I'm running ubuntu 18.04

**Comment by adrienbernede** [comment]
And what architecture is spack detecting? (`spack arch`)
We provide a spack configuration for `linux-ubuntu18.04-broadwell`, I would like to know if your spack is using it, or starting from scratch.

**Comment by samanseifi** [comment]
I confirm `linux-ubuntu18.04-broadwell` is what I get from my `spack arch`.

**Comment by samanseifi** [comment]
> Hi, similar errors have shown up as a result of serac using an old version of spack. Can you try replacing the project.json file from the one in the bump_spack_version branch and see if that helps?
> 
> https://github.com/LLNL/serac/blob/bump_spack_version/scripts/uberenv/project.json

this did not help @samuelpmish

**Comment by adrienbernede** [comment]
If I were you, I would try to clean up some stages:
- `spack purge --misc-cache` because this one is defined in `~/.spack`, so might collide with another spack instance.
- `spack purge --stage` to make sure spack restart building from scratch.

You have to load the right spack to do that (or use the right spack binary):
`cd uberenv_libs && . spack/share/spack/setup-env.sh`

**Comment by samanseifi** [comment]
Problem still exist :(

**Comment by samuelpmish** [comment]
is the package that produces the error cmake@3.15.5?

What do you get when you run

`./path/to/serac/uberenv_libs/spack/bin/spack --version`?

**Comment by white238** [comment]
I think this might be coming from the CMake package...

Do you have CMake installed on your system? If so change the following path in scripts/uberenv/spack_configs/linux-ubuntu18.04-broadwell/packages.yaml:

  cmake:
    paths:
      cmake: /usr
    buildable: False

If you don't have it installed (and i really recommend you do because it takes a while to install), you can can change the above lines to this:

  cmake:
    version: [3.9.6]

To try to avoid the bad patch

**Comment by samuelpmish** [comment]
On my machine, your error comes from trying to install cmake@3.15.5:

```
~/serac/uberenv_libs/spack/bin$ ./spack --version
0.13.2

~/serac/uberenv_libs/spack/bin$ ./spack stage cmake@3.15.5

==> Error: sha256 checksum failed for /tmp/sam/spack-stage/spack-stage-8ch53v5s/4075.patch
Expected 3387faf4a71efe81c0fa17410b270ca7d352081ac88d2322df3da9bb6a6a3f2d but got 42d8b2163a2f37a745800ec13a96c08a3a20d5e67af51031e51f63313d0dedd1
```

but after checking out a more recent version of spack (from bump_spack_version branch project.json)
```
~/serac/uberenv_libs/spack/bin$ git checkout 0c7fff60651

~/serac/uberenv_libs/spack/bin$ ./spack --version
0.14.1-433-0c7fff606
```
it can handle cmake@3.15.5 successfully
```
~/serac/uberenv_libs/spack/bin$ ./spack stage cmake@3.15.5
==> Fetching https://github.com/Kitware/CMake/releases/download/v3.15.5/cmake-3.15.5.tar.gz
###################################### 100.0%
###################################### 100.0%
==> Staging archive: /tmp/sam/spack-stage/spack-stage-cmake-3.15.5-6z3fks2zjax2twzuicotskwi7ylvbni5/cmake-3.15.5.tar.gz
==> Created stage in /tmp/sam/spack-stage/spack-stage-cmake-3.15.5-6z3fks2zjax2twzuicotskwi7ylvbni5
```

What worked for me was to delete the old version of spack, use the project.json with a more recent version and try building again.
```
~/serac$ rm -rf uberenv_libs/spack/

~/serac$ git checkout bump_spack_version scripts/uberenv/project.json

~/serac$ python3 scripts/uberenv/uberenv.py
```

@adrienbernede 'purge' doesn't seem to be a spack command, is `clean` the same thing?

**Comment by adrienbernede** [comment]
@samuelpmish 
It must have been, a long time ago 😅. `spack clean` replaced it indeed.

**Comment by samanseifi** [comment]
@samuelpmish Yes that is correct I had the `cmake` problem. I did try bunch of these things and it seems to be working now! I'll build it in my other machine (also ubuntu 18.04) again to make sure this is resolved. My question is why there is a need to pull a `spack` instance for serac seperately? I already have `spack` (for building `mfem` with bunch of its libraries). I have two spacks and two mfems now and so many other libraries. What am I missing here?

**Comment by white238** [comment]
You don't have to build mfem through our suggested way but this is the way we have vetted and recommend.  If you wish to do everything yourself you can just point your already built mfem to our cmake system with defining MFEM_DIR.  This can be done with either ./config-build.py or running cmake directly with -DMFEM_DIR=<path/to/mfem/install>.

If you go this way you will need to define other cmake variables that are output by the serac spack package in our host-configs.  You can see examples of them in host-configs/

**Comment by white238** [comment]
#43 will fix this issue

**Comment by samanseifi** [comment]
OK. So I changed the serac's local `mpiexec` set in the cmake file to my `mpiexec` in `/usr/bin/mpiexec`. All tests are passed, but when I run  `ctest -R blt_mpi_smoke --verbose ` this is what I get:
```
2: Test timeout computed to be: 1500
2: Count should be equal to rank size
2: Count = 1, Size = 1
2: Count should be equal to rank size
2: Count = 1, Size = 1
2: Count should be equal to rank size
2: Count = 1, Size = 1
2: Count should be equal to rank size
2: Count = 1, Size = 1
```
But I don't think that's correct.

**Comment by jamiebramwell** [comment]
This appears to be a problem with your MPI install. I would check with the [spack project](https://github.com/spack/spack) to help troubleshoot the issue. I've also lowered the number of processes used in our tests to 2, so that should help.
