### ISSUE TITLE
Change the LGTM tests to run against the checked in host-configs

### ISSUE THREAD

**Issue by white238** [LLNL/serac#47]
This will speed up the turn around and limit the amount we hog machines during the day.  Then have the full TPL build only go at night.  This will also guard against system changes.

**Comment by adrienbernede** [comment]
Do you need me to do it?

**Comment by white238** [comment]
This was a more of a don't let me forget.  But if you are looking for something to do, by all means =)

**Comment by adrienbernede** [comment]
:) the next question was "for when" because I have enough on my plate actually. Still it shouldn’t be hard to do.

**Comment by white238** [comment]
Then definitely don't worry about it.  I can handle it eventually. It has no pressing need.
