### ISSUE TITLE
NVCC had issue compiling static constexpr member variable in struct.

### ISSUE THREAD

**Issue by jonwong12** [LLNL/serac#486]
for context, this change was made because only `shape[0]` was being used, and nvcc was having trouble compiling `static constexpr` C-array members

_Originally posted by @samuelpmishLLNL in https://github.com/LLNL/serac/pull/478#discussion_r646964322_

**Comment by samuelpmishLLNL** [comment]
The current implementation in `develop` already has workarounds for this limitation of `nvcc`, but I'll try to explain in more depth the issue and a potential workaround.

This code (accessing a `static constexpr` member on a type, in a cuda kernel) works, even without `--expt-relaxed-constexpr`:

```cuda
#include <cstdio>

struct foo { static constexpr int number = 6; };

__global__ void printing_with_foo(){
  printf("%i", foo::number);
}

int main() { printing_with_foo<<<1,1>>>(); }
```

but this code (accessing a `static constexpr` C-style array member in a cuda kernel) doesn't, even with `--expt-relaxed-constexpr`:

```cuda
#include <cstdio>

struct foo {
  static constexpr int numbers[3] = {6, 28, 496};
};

__global__ void printing_with_foo(){
  // error: identifier "foo::numbers" is undefined in device code
  printf("%i, %i, %i", foo::numbers[0], foo::numbers[1], foo::numbers[2]); code
}

int main() { printing_with_foo<<<1,1>>>(); }
```

One workaround is to store `static constexpr` array-like data in a `__device__`-compatible, copy-able container and do something like

```cuda
#include <cstdio>

struct three_integers { 
  int values[3]; 
  __device__ const int & operator[](int i) const { return values[i]; }
};

struct foo {
  static constexpr three_integers numbers = {6, 28, 496};
};

__global__ void printing_with_foo(){
  static constexpr auto tmp = foo::numbers;
  printf("%i, %i, %i", tmp[0], tmp[1], tmp[2]);

  // note: doing printf("%i, %i, %i", foo::numbers[0], foo::numbers[1], foo::numbers[2]); still doesn't work
}

int main() { printing_with_foo<<<1,1>>>(); }
```

**Comment by nvjonwong** [comment]
@samuelpmishLLNL Just for documentation purposes, I think if you replace the c-style array with `std::array<int>` it may work.

```
struct foo {
  static constexpr std::array<int, 3> numbers = {6, 28, 496};
};
```
