### ISSUE TITLE
Make a serac-specific cmake testing macro

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#520]
Lets do the testing macro in a followup PR.  We can probably just have one macro something like:

```
serac_add_test(SOURCE file
                         DEPENDS_ON list
                         COMMAND_ARGS -something-here
                         NUM_MPI_TASKS 4)
```

where NUM_MPI_TASKS is optional and triggers the serial/parallel

_Originally posted by @white238 in https://github.com/LLNL/serac/issues/515#issuecomment-885146488_

**Comment by joshessman-llnl** [comment]
Resolved by #522
