### ISSUE TITLE
Update MFEM to 4.3

### ISSUE THREAD

**Issue by joshessman-llnl** [LLNL/serac#532]
MFEM 4.3 has been released: https://github.com/mfem/mfem/releases/tag/v4.3

We should upgrade and enable `hypre+cuda` to take advantage of the corresponding functionality in MFEM

**Comment by samuelpmishLLNL** [comment]
I think there are some bug-fixes in 4.3 that are relevant to enabling boundary integrals over Hcurl spaces as well (but I'm not sure if they ever addressed the missing ElementRestriction implementations).
