### ISSUE TITLE
Clean up the GPU kernel names

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#549]
I discussed this with Jonathan last week, our plan was to make them into overloads of the 3 fundamental kernels
```cpp
evaluation< execution_space >
directional_derivative< execution_space >
gradient_matrix< execution_space >
```
for consistency

_Originally posted by @samuelpmishLLNL in https://github.com/LLNL/serac/pull/523#discussion_r690494784_

**Comment by samuelpmishLLNL** [comment]
Closing, the relevant kernels have been renamed consistently:

```cpp
evaluation_kernel
action_of_gradient_kernel
element_gradient_kernel
```

the cuda versions use the same name, with a `_cuda` suffix
