### ISSUE TITLE
Our operator overloading expression templates don't work with the GPU

### ISSUE THREAD

**Issue by jonwong12** [LLNL/serac#550]
I'm not sure if we noted it explicitly, but our operator overloading expression templates don't work with the GPU (mfem's memory management model makes it difficult to reason about what those expressions should do).

_Originally posted by @samuelpmishLLNL in https://github.com/LLNL/serac/pull/523#discussion_r689815620_

**Comment by jamiebramwell** [comment]
We should add warnings around them if this is attempted.

**Comment by jonwong12** [comment]
Can you remind me how to reproduce the issue? @samuelpmishLLNL 

@jamiebramwell is there a base docker file or docker image I can use to reproduce the issue?

**Comment by jonwong12** [comment]
@samuelpmishLLNL can you remind me how I can reproduce the issue. It’s been awhile.

@jamiebramwell is there a docker I can use or dockerfile to reproduce the issue?

I can take a look when I get the chance.

**Comment by samuelpmishLLNL** [comment]
In my mind, there are two main issues. 

The first is simply that Josh wasn't targeting GPUs when writing this implementation, so there's a bunch of little stuff that won't work on a GPU (nothing is host/device decorated, there are [raw loops](https://github.com/LLNL/serac/blob/develop/src/serac/numerics/vector_expression.hpp#L44-L51) on the host that won't work, etc).

The trickier issue is related to how `mfem::Vector` handles GPU memory in a confusing way (I think you have to opt-in with `mfem::Vector::UseDevice(bool)`), which means it's unclear what an expression like 

```cpp
mfem::Vector result = 3.0 * a - b * 3.0 + c;
```

should even do for the different combinations of `a`, `b`, `c` having opted-in (or not) to using GPU memory.

**Comment by jonwong12** [comment]
Thanks for the explanation. I think point 2 is poignant and requires more clarity. I’d be happy to help if there is a specific use case and/or ask related to gpus.
