### ISSUE TITLE
Integrating with axom policies

### ISSUE THREAD

**Issue by jonwong12** [LLNL/serac#551]
I think we should keep it as-is for now. Integrating with axom policies can be part of a follow on PR.

_Originally posted by @jamiebramwell in https://github.com/LLNL/serac/pull/523#r689891678_

**Comment by samuelpmishLLNL** [comment]
I believe this is resolved in `develop` now. For clarification: axom's policies include specific details about how the underlying algorithms should be performed, whereas the objects in `Functional` just needed a coarser choice between: use CPU or use GPU. In `develop` now is `serac::ExecutionSpace` which defines these two options. We may still later use axom policies later on, if we have to select from many different implementations of a given algorithm (but we are not there yet). 

@jamiebramwell should we close this issue?
