### ISSUE TITLE
Output which datacollection file we are about to save

### ISSUE THREAD

**Issue by white238** [LLNL/serac#578]
Outputting the name of the root of the datacollection file we are writing to would help a lot when debugging file system issues.

Something like the following in `void StateManager::save`:

```
 // this could be expanded on i think
  std::string file_path = axom::utilities::filesystem::joinPath(datacoll_->GetPrefixPath(), datacoll_->GetCollectionName());
  SLIC_INFO_ROOT(fmt::format("Saving data collection: {}", file_path));
```

**Comment by joshessman-llnl** [comment]
File I/O seems to be particularly fragile for us, I think it would make sense to `SLIC_INFO` whenever we write to/read from a file (i.e., beyond just the datcollection saves)
