### ISSUE TITLE
Add `asan` variant to Serac's `mfem` Spack package

### ISSUE THREAD

**Issue by goxberry** [LLNL/serac#579]
Essentially a continuation of #531, only this time, add an `+asan` variant for Serac's version of the `mfem` package. Theoretically, if Spack packages are supposed to compose compiler flags injected via specs (e.g., by adding `cxxflags="-faddress=sanitize"`), then this probably wouldn't be necessary, but in practice, this approach rarely seems to work. LiDO inherits (read: copies) its `mfem` Spack package from Serac, and LiDO needs to add this sort of variant to help us with debugging a memory problem we're encountering in a case study at scale. If you guys are interested, I'd be happy to contribute this change to Serac so that both projects could benefit; if not, no worries -- I can add it to the LiDO version of the `mfem` Spack package instead.

**Comment by white238** [comment]
@goxberry did this a while back...
