### ISSUE TITLE
Material response in hyperelasticity formulation possibly wrong

### ISSUE THREAD

**Issue by termi-official** [LLNL/serac#586]
Hi folks,
I have played around with serac to find a good angle on good ways to implement hyperelasticity on top of MFEM and run into a bug. I would like to propose a complete fix, but I could not pin it down exactly over serveral days of hunting it.

## Problem description
Utilizing the provided Neo-Hookean implementation yields faulty results. It looks like some components has been mixed up somewhere in the solution process, but I could not find which after double checking the implementation against the referenced derivation. As a test setup I have a simple cube which I fix on one side and pull on the other side. To make sure I did nothing wrong I integrated the integrator with the model into a modification of MFEM example 19 (removing the pressure, can post it on demand). The result is as follows

![serac-vs-mfem-hyperelasticity](https://user-images.githubusercontent.com/9196588/139350920-5f3a53e4-5627-4182-969b-c934e7b2e488.png)

where left is the solution of serac's integrator/model pair and on the right the example 19 solution in mfem. Note that the constriction is the correct material response. The same "inverted" material response is visible when the cube is pushed instead of pulled, i.e. in serac the material constricts, where it should expand. At least that is what I would expect here.

## MWE
<details>
 <summary>Serac input script</summary>

```lua
-- Comparison information
expected_u_l2norm = 0.015934784
epsilon = 0.001

-- Simulation time parameters
dt      = 1.0

main_mesh = {
    type = "file",
    -- mesh file
    mesh = "../../../meshes/cube.mesh",
    -- serial and parallel refinement levels
    ser_ref_levels = 0,
    par_ref_levels = 0,
}

-- Simulation output format
output_type = "GLVis"

-- Solver parameters
solid = {
    equation_solver = {
        linear = {
            type = "iterative",
            iterative_options = {
                rel_tol     = 1.0e-6,
                abs_tol     = 1.0e-8,
                max_iter    = 5000,
                print_level = 0,
                solver_type = "minres",
                prec_type   = "L1JacobiSmoother",
            },
        },

        nonlinear = {
            rel_tol     = 1.0e-3,
            abs_tol     = 1.0e-6,
            max_iter    = 5000,
            print_level = 1,
        },
    },

    -- polynomial interpolation order
    order = 2,

    -- neo-Hookean material parameters
    mu = 1.0,
    K  = 0.1,

    initial_displacement = {
        vector_constant = {
            x = 0.0,
            y = 0.0,
            z = 0.0
        }
    },

    initial_velocity = {
        vector_constant = {
            x = 0.0,
            y = 0.0,
            z = 0.0
        }
    },

    -- boundary condition parameters
    boundary_conds = {
        ['displacement'] = {
            -- boundary attribute 1 (index 0) is fixed (Dirichlet) in the x direction
            attrs = {1},
            vector_constant = {
                x = 0.0,
                y = 0.0,
                z = 0.0
            },
        },
        ['traction_ref'] = {
            attrs = {2},
            vector_constant = {
                x = 0.1,
                y = 0.0,
                z = 0.0
            },
        }
    },
}
```
</details>

<details>
  <summary>Tested cube geometry</summary>

```
MFEM mesh v1.0

#
# MFEM Geometry Types (see mesh/geom.hpp):
#
# POINT       = 0
# SEGMENT     = 1
# TRIANGLE    = 2
# SQUARE      = 3
# TETRAHEDRON = 4
# CUBE        = 5
# PRISM       = 6
# PYRAMID     = 7
#

dimension
3

elements
1
1 5 0 1 3 2 4 5 7 6

boundary
6
3 3 0 2 3 1
3 3 4 5 7 6
1 3 0 4 6 2
2 3 1 3 7 5
3 3 0 1 5 4
3 3 2 6 7 3

vertices
8
3
0 0 0
1 0 0
0 1 0
1 1 0
0 0 1
1 0 1
0 1 1
1 1 1
```
</details>

## What I know so far
1. If I see it correctly, then the sign of the residual vector is flipped.
2. I am lost on why the Newton converges in both implementations. Printing the element residuals suggests that in the serac integrator the element residuals are not converged when the Newton converges. (Edit note: I think the Newton just checks if the increment converges, not the actual residual, c.f. https://github.com/mfem/mfem/blob/72204b7f0166870d43b2ebd243c27c772778b0bb/linalg/solvers.cpp#L1730-L1735)
3. Flipping the residual's sign gives a good response in the first few Newton iteration, but the residual diverges. This suggests to me that some of the components in the stress/material tangent/... could be switched, but I could not find it after several tries. Here a simulation on a finer grid with the second and third newton iteration using the serac integrator.
![serac-hyperelasticity-residual-signflip](https://user-images.githubusercontent.com/9196588/139353376-334f7a89-9fd1-4602-8d2e-0b3bfddb8326.png)
where the direction into which we pull looks strangely off (+- the residual and way too strong constriction :)). The next Newton step diverges.

**Comment by samuelpmishLLNL** [comment]
hi @termi-official, thanks for creating this thorough write-up! 

It's after hours so I don't have a chance to look into it too closely right now, but I did notice the following lines in the input file:

```
    -- neo-Hookean material parameters
    mu = 1.0,
    K  = 0.1,
```

This looks like an unusual choice of elasticity parameters, the Poisson's ratio for these values is large and negative (!):

<img src="https://user-images.githubusercontent.com/61714427/139363818-30eab1d8-f671-43ab-b56b-a7ef9126655e.png" width=50% height=50%>

which is technically consistent with the response of expanding when pulled (whether or not there is a real material that actually does that is a separate question). Is it possible you meant to specify `K = 1.0` and `mu = 0.1` instead?

That being said, I think this material model is not extensively tested, so it's entirely possible that we've missed a minus sign (or several). We'll investigate this soon and see if we can figure out what's going on.

**Comment by termi-official** [comment]
Hi @samuelpmishLLNL ,

thanks for the quick response. I was not aware of this and hit by chance negative Poisson ratios for all my choices, so also thanks for the elaboration and the quick catch! Going through the relevant code again the sign of the residual for the Newton should also be correct, as, if I understand the implementation correctly, the Newton takes `-increment` as the solution.

Best regards,
Dennis
