### ISSUE TITLE
Wondering about distributing/assembling dual vectors

### ISSUE THREAD

**Issue by tuckerbabcock** [LLNL/serac#588]
Hi All,

I've been taking a look at the serac code after the MFEM workshop, and I really like the idea of the FiniteElementVector/State/Dual classes, but I've got a question about the implementation of `distributeSharedDofs` and `initializeTrueVec` for the case of the `FiniteElementDual` vectors. Based on this link: https://mfem.org/pri-dual-vec/, it looks like the conversion between dof and tdof vectors should be different for duals than for primal vectors. Here's the current implementation for all `FiniteElementVectors`:
https://github.com/LLNL/serac/blob/bd229c48c5ddf4c6e3c1dcaa815a40caaa670094/src/serac/physics/state/finite_element_vector.hpp#L135-L144

And I'm essentially wondering why this function isn't different for duals, something like
```
void distributeSharedDofs() { detail::retrieve(gf_).???(true_vec_); }

void initializeTrueVec() { detail::retrieve(gf_).ParallelAssemble(true_vec_); }
```
With the question marks in `distributeSharedDofs` since I couldn't find any `GridFunction` method that would multiply `gf = R^T tv`.

Thanks!

**Comment by tuckerbabcock** [comment]
I guess `distributeSharedDofs` could look like:
```
void distributeSharedDofs()
{
  detail::retrieve(space_).GetRestrictionMatrix->MultTranspose(true_vec_, detail::retrieve(gf_));
}

**Comment by jamiebramwell** [comment]
Yes, you are absolutely correct. I think we didn't notice this because we don't use non-conforming meshes. I'll put up a PR to fix it.

**Comment by tuckerbabcock** [comment]
Great, thanks!
