### ISSUE TITLE
*Solver objects unsafe

### ISSUE THREAD

**Issue by samuelpmishLLNL** [LLNL/serac#6]
There's a lot of use of raw pointers in the BaseSolver and related classes. Aside from being ambiguous about ownership, it also means that something as simple as passing one of these objects to a function will segfault.
```
template < typename T >
T do_anything(T foo) {
  ...
}

DynamicSolver oper(...);
do_anything(oper); // $ Segmentation fault (core dumped)
```
My vote is to just avoid raw pointers as much as is practical (in favor or std::shared_ptr or reference variables), but we could also disable some copy constructors and make these objects move-only.

**Comment by jamiebramwell** [comment]
One of the items on my todo list is to move all of the raw pointers over to shared pointers. This has fallen down the priority list in favor of getting the initial implementations done. Are you interested in taking a stab at this @samuelpmishLLNL ? `BaseSolver` and `ThermalSolver` should be ready to go at this point. Any thoughts, @white238 ?

**Comment by samuelpmishLLNL** [comment]
I can transition things into shared_ptr, but I'm not too familiar with most of these mfem data types. Can you think of any cases where things would need to stay raw pointers?

**Comment by jamiebramwell** [comment]
I can't think of any. I know Jonathan Wong has done something similar for LiDO, so he might be a good resource.

**Comment by white238** [comment]
Thanks for logging the issue @samuelpmishLLNL .  This has always been on our radar but we were putting it off until we got a few more features in and rounded out ideas.  Though we probably let it slip too long.

We should be using shared_ptr in as many places as possible.  It helps to be clear that we are not passing ownership of the memory to what we are sharing it with.  When we are passing ownership (like a factory method), we should be using unique_ptr.  This makes it very clear that they own the data and the caller can then convert the unique_ptr to a shared_ptr if they want.

We should be limiting our use of raw pointers (which you can always get from the C++11 pointers) to only where we need to: interacting with legacy code and serious performance reasons.

Also don't forget references are great too.  Don't want to make them feel left out.
