### ISSUE TITLE
Allow test checker to handle tolerances on per-field basis

### ISSUE THREAD

**Issue by white238** [LLNL/serac#601]
It would be nice if we could specify this on a per-field basis, but that could be a follow-on PR.

_Originally posted by @jamiebramwell in https://github.com/LLNL/serac/pull/598#discussion_r755388079_

Options:

* file that has tolerances in it listed: `--tolerances=mytolerances.json`
* parsed comandline string: `--tolerances=velocity:0.1::displacement:0.234`

**Comment by jamiebramwell** [comment]
I was thinking the json-file way, but it would be nice if we could also do it on the command line.

**Comment by white238** [comment]
Add command line option to load a json file that has per-field tolerances.  We should allow either a global on the command line via the existing `--tolerances` option or a new option `--tolerance-file` that loads a json file that has all of them with an optional default tolerance.

Something like this:

tolerance_test.py --tolerance-file=test_tolerances.py
```
{
 "default": 0.0001,
 "velocity": 0.001,
 "displacement":0.01
}
```
