### ISSUE TITLE
Suggestion: specifying non mandatory variants in packages.yaml

### ISSUE THREAD

**Issue by adrienbernede** [LLNL/serac#63]
https://github.com/LLNL/serac/blob/553f454f821d74ab032655d7f03ecb6eb1f10ee9/scripts/uberenv/packages/serac/package.py#L91

@white238 I think it would be better to specify variants that are not mandatory in the packages.yaml (EDIT: not host-config files). This way it does not force the installation of a new axom if one is already present for example, and developer can still install the blessed configuration with uberenv.

**Comment by white238** [comment]
Did you mean the packages.yaml? Variants don't go in host-configs. Variants can go in the packages file but then they have to be duplicated in everyone we have.

I think it would be better to step back and figure out what are you trying to accomplish with this?  The serac package is very specialized to us and we want to build our libraries as a whole package.  If we want, we can push a more generic version up to Spack but optimizations are going to be common in this file going forward.  If we remove, for example, raja and umpire from that list, we would be solving your problem but requiring all of our developers to build at least two packages we don't currently use.

**Comment by adrienbernede** [comment]
Sorry, yes, packages.yaml of course... And yes, there would be a bit of a duplication.
Taking the example of raja and umpire, don’t you think it is "enough" to put those variant in the packages.yaml?

I understand you are looking at this from a specific application. But in my experience in Spack, it’s always best to allow the package to be built in the most configuration possible. It does not prevent from having optimized or specific variants even defined in the package.

**Comment by white238** [comment]
This is not about what is best for Spack, it is what is best for this project.  This specific serac package.py is ours and will be tuned to our needs.

In fact, I ran into a just problem today with the versions being in the packages.yaml. So this is already a problem.

**Comment by adrienbernede** [comment]
So be it. I didn’t mean best for Spack. I guess we will see with time.

Having a "public" serac package with a generic configuration sounds appealing, but I think it will bring a lot of issues because of the coexistence of a two packages.

**Comment by adrienbernede** [comment]
@jamiebramwell @white238 should we close this one?

**Comment by jamiebramwell** [comment]
I'll leave that to @white238 ! I think we do want to have a hard lock on our dependencies in general, so I vote for closing it.

**Comment by white238** [comment]
We can readdress this when the new concretizer is more stable/widely used.
