### ISSUE TITLE
AMGX .lua input files failing due to AMGX not being enabled in MFEM 

### ISSUE THREAD

**Issue by chapman39** [LLNL/serac#651]
when running serac on `dyn_amgx_solve.lua` and `static_amgx_solve.lua`, I get the following error:

`ERROR (/usr/WS2/meemee/serac/repo/src/serac/numerics/equation_solver.cpp:147)]
AMGX was not enabled when MFEM was built`

**Comment by white238** [comment]
related to #657

**Comment by jamiebramwell** [comment]
This test fails because it can only run on CUDA-enabled machines.

**Comment by chapman39** [comment]
Fixed by https://github.com/LLNL/serac/pull/682
