### ISSUE TITLE
qs_attribute_solve_parallel test fails (sometimes)

### ISSUE THREAD

**Issue by chapman39** [LLNL/serac#668]
When running `./ats.sh`, qs_attribute_solve_parallel takes a long time to converge (about 3 minutes). According to the logs, it tries 5000 iterations before it gives up. The tolerances that fail seem to switch between two values:

> ERROR: Test value 'displacement/l1norms[0]' out of tolerance: baseline value=0.0996687535543166, test value=1.95006410505963
> ERROR: Test value 'displacement/l2norms[0]' out of tolerance: baseline value=-0.216814893270359, test value=3.0725532465425
> ERROR: Test value 'displacement/linfnorms[0]' out of tolerance: baseline value=20.3046995090693, test value=13.7850688348039
> ERROR: Test value 'displacement/avgs[0]' out of tolerance: baseline value=0.29714063702572, test value=-0.407641749981539
> ERROR: Test value 'displacement/mins[0]' out of tolerance: baseline value=-6.88522152649478, test value=-18.488253015702
> ERROR: Test value 'displacement/maxs[0]' out of tolerance: baseline value=24.5078855697869, test value=4.95114675337821

Runs totally fine serially, though.

**Comment by jamiebramwell** [comment]
It looks like this is still a problem. We should re-investigate and add this test back once the input deck interface is hooked up to the `Functional`-based solid module.

**Comment by jamiebramwell** [comment]
`dyn_linesearch_solve.ats` is also intermittently failing.
