### ISSUE TITLE
Git SHA header is not installing properly in downstream projects

### ISSUE THREAD

**Issue by white238** [LLNL/serac#677]
Noticed by @jamiebramwell  in a Smith update.

We should also add one to Smith if its not there and make sure both exist together.

**Comment by jamiebramwell** [comment]
@white238 , is this still an issue?

**Comment by white238** [comment]
I don't think this is an issue but we should check.  @chapman39 can you verify this in LiDO?

**Comment by chapman39** [comment]
yup seems to be installing fine
