### ISSUE TITLE
Store geometry information in the `Functional` integrals

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#728]
We currently use the mesh node coordinates, jacobians, and normals stored internally to the active `mfem::Mesh`. However, this data can become stale and we have to manually delete the data if the mesh is updated. Instead, we should generate and store this mesh information ourselves within the `DomainIntegral` and `BoundaryIntegral` classes.

**Comment by samuelpmishLLNL** [comment]
I think this one was resolved a few months back: https://github.com/LLNL/serac/blob/ef92950b75ee323a8754fa64b274d65a95925258/src/serac/numerics/functional/integral.hpp#L180-L181
