### ISSUE TITLE
Enable ParaView visualization of results

### ISSUE THREAD

**Issue by barreracruz** [LLNL/serac#732]
Allow the user to output results in ParaView format. @jamiebramwell @samuelpmish

**Comment by samuelpmish** [comment]
In the long term, I think we should make an issue / feature-request with axom or Paraview, asking if it's feasible to make Sidre output readable by ParaView.

**Comment by jamiebramwell** [comment]
Apparently that was discussed on the Axom team at one point. I'm asking around what the current state of that feature is.
