### ISSUE TITLE
Make "bank" overridable by environment variable

### ISSUE THREAD

**Issue by adrienbernede** [LLNL/serac#74]
Most pipelines should be run with the project bank. But when triggering a pipeline from the outside (multi-project) or manually, the bank may not be accessible.

A solution would be to make the bank overridable by environment variable.

**Comment by jamiebramwell** [comment]
As more people are contributing to the repo without `eng` access, I think this should get bumped up the priority list.

**Comment by adrienbernede** [comment]
More details about this topic:
:white_check_mark: We can already manually change the bank and queue for pipelines triggered manually or from another project: by overriding `SLURM_ACCOUNT` and `LSF_ACCOUNT` in the UI or in the trigger job.
:white_check_mark: This also allows a developper without access to `eng` to configure his personal serac clone on Gitlab to run on a different bank: the variables can be overridden in the repo settings.
:no_entry_sign: This does not allow a user outside `eng` to push a branch in serac and automatically trigger a valid pipeline.

**Comment by white238** [comment]
This was fixed by @adrienbernede  in #482
