### ISSUE TITLE
Change from MFEM's command line arguments to CLI11

### ISSUE THREAD

**Issue by white238** [LLNL/serac#76]
Axom has built in support for CLI11.  We should switch to that and away from MFEM's.  CLI11 is more industry standard and is C++ vs C (ie std::strings vs char*).

**Comment by joshessman-llnl** [comment]
There is a slight difference in functionality: CLI11 only [supports single-character short names](https://github.com/LLNL/axom/blob/develop/src/thirdparty/CLI11/CLI11.hpp#L1374) (those preceded by a single `-`).   From a usability standpoint, does it make more sense to shorten the short names, or to make them long names, e.g., for refining the mesh in serial, should `-rs` change to `-s` or `--rs`?
