### ISSUE TITLE
Stress in residual operator contracted on wrong index

### ISSUE THREAD

**Issue by btalamini** [LLNL/serac#773]
The functional-based solid mechanics operator uses a total Lagrangian setting, so it uses the first Piola-Kirchhoff stress in the residual calculation. However, in the kernel [here](https://github.com/LLNL/serac/blob/5aeeea93f029d3b3afcbe30e9ce39253c1ea77e8/src/serac/numerics/functional/integral_utilities.hpp#L523) the stress is contracted with the shape function derivatives on its first index, which is the wrong one. 

Needed: fix this in a dimensionally independent way, so both scalar and vector-valued primal field problems work.

**Comment by jamiebramwell** [comment]
@samuelpmishLLNL , did we decide to leave it the way it is?

**Comment by btalamini** [comment]
This bug was fixed in #779 (by transposing the Piola-Kirchhoff stress):

https://github.com/LLNL/serac/blob/7a6ef7a6e7e502608c21d2ef1fc0a43fedd3fef5/src/serac/physics/solid_mechanics.hpp#L393-L402

However, as you can see, the comments written there treat this fix as temporary. I think we're now taking the view that this is a design requirement: the rightmost index of the flux needs to be the one that contracts with the test function gradient index. We can close the issue, but we should update the comments and the documentation.

**Comment by jamiebramwell** [comment]
That's fair. I'll leave this open as an issue to better update the documentation.
