### ISSUE TITLE
Fails to build: Given AXOM_DIR did not contain a required header: axom/sol.hpp

### ISSUE THREAD

**Issue by yurivict** [LLNL/serac#775]
The latest version axom-0.6.1 doesn't install ```axom/sol.hpp```.

**Comment by white238** [comment]
Can you give some more information?  What instructions were you following? Where did you build it from?

Axom does not turn on Sol functionality or install Sol unless you build with `axom+lua+cpp14` in Spack, which is default in all the places I know of but there is certainly ways to turn it off.

**Comment by yurivict** [comment]
Axom is built from the [FreeBSD port](https://cgit.freebsd.org/ports/tree/science/axom/Makefile).
It doesn't seem to have Sol functionality enabled.

I am not sure why does ```serac``` expect to find ```axom/sol.hpp``` in axom.

**Comment by white238** [comment]
Axom ship a guarded (and non-C++17) Sol. Axom enables its internal Sol support by the following two CMake arguments:

```
-DLUA_DIR=/path/to/lua/install 
-DBLT_CXX_STD=c++14
```

The latter will be default in the next release of Axom, which is hopefully very soon.

**Comment by white238** [comment]
You will also need to give Axom the command line option `-DMFEM_DIR=/path/to/mfem/install` because we also rely on the `MFEMSidreDataCollection` class which is only enabled if you point Axom at MFEM.

**Comment by yurivict** [comment]
Thanks, Chris.

The original error is gone with options that you've recommended for Axom.
