### ISSUE TITLE
error: no member named 'HypreSmoother' in namespace 'mfem'

### ISSUE THREAD

**Issue by yurivict** [LLNL/serac#777]
```
In file included from /disk-samsung/freebsd-ports/science/serac/work/serac-5aeeea9/src/serac/infrastructure/input.cpp:16:
/disk-samsung/freebsd-ports/science/serac/work/serac-5aeeea9/src/serac/infrastructure/../../serac/numerics/solver_config.hpp:128:9: error: no member named 'HypreSmoother' in namespace 'mfem'
  mfem::HypreSmoother::Type type;
  ~~~~~~^
```

mfem is installed both separately and as a git submodule.

**Comment by white238** [comment]
Had to look this up.  MFEM has two build systems, I am not sure which one you are using, so here are both.

Makefile:
```
HYPRE_OPT=-I/hypre/include/path
HYPRE_LIB=<hypre link flags>
```

CMake:
```
-DHYPRE_DIR=/path/to/hypre/install
```

**Comment by yurivict** [comment]
What MPI implementation are all these projects supposed to use? mpich or OpenMPI?

**Comment by white238** [comment]
It depends on the platform.  We don't use a specific one.

**Comment by jamiebramwell** [comment]
Yes, to resolve this you need to compile the MPI-enabled version of MFEM. Any MPI version should work. We are not compatible with the serial version of MFEM.
