### ISSUE TITLE
untangling target/test dependencies

### ISSUE THREAD

**Issue by samuelpmishLLNL** [LLNL/serac#788]
Chris and I noticed that a lot of the CMake targets in serac have unnecessarily repeated dependencies:

![serac_target_dependencies](https://user-images.githubusercontent.com/61714427/188960785-71ab595f-41ae-492a-8d16-b9ad23f2b8d2.png)

In blue are the current explicitly defined intra-target dependencies, and in red are the essential dependencies after transitive reduction. Note: the targets ("physics_materials", "coefficients" and "integrators") are associated with the pre-`Functional` implementation and may be deprecated / removed.

Unfortunately, cleaning this up is trickier than expected, as the tests for each of these targets don't respect their associated locations in the project hierarchy. For example, the target `serac_infrastructure` is a leaf-node of the serac project (it has some external dependencies), but the tests in `serac/infrastructure/tests` depend on `serac_physics` (which itself depends on essentially everything in serac).

This is a bad habit, and I think it would be beneficial to untangle the tests such that their location in the project reflect the features under test. Tests should be placed in most nested directory as appropriate (i.e. the narrowest scope). So, a test that depends only on `serac_infrastructure` should be in `serac/infrastructure/tests` rather than `serac/tests`. Similarly, if a test depends on a lot more than `serac_infrastructure`, it should be in a parent directory, rather than in `serac/infrastructure/tests`.

**Comment by chapman39** [comment]
Not everything mentioned here is resolved. I believe this PR https://github.com/LLNL/serac/pull/860 will completely close the issue
