### ISSUE TITLE
CI jobs potentially being duplicated (?)

### ISSUE THREAD

**Issue by samuelpmishLLNL** [LLNL/serac#799]
When making a commit to https://github.com/LLNL/serac/pull/663, I noticed that it caused two CI jobs to start simultaneously:

https://dev.azure.com/llnl-serac/serac/_build/results?buildId=7792&view=results
https://dev.azure.com/llnl-serac/serac/_build/results?buildId=7793&view=results

I'm unfamiliar with the specific details of our CI system, so I'm not sure if this is intended (or misinterpreted by me), or if we're accidentally triggering redundant CI jobs.

**Comment by jamiebramwell** [comment]
I believe this is intended behavior. Any comments @white238 ?

**Comment by white238** [comment]
I was planning on hand testing this to make sure it is doing what I believe it was doing..
