### ISSUE TITLE
Shape sensitivity bugs in solid mechanics

### ISSUE THREAD

**Issue by btalamini** [LLNL/serac#806]
Dan T found what he and I think are bugs in the shape sensitivity calculations. I'm mad at myself with not catching these when we reviewed it.

The first is here: 
https://github.com/LLNL/serac/blob/7cf216a1be68719dc997f393d741070f1dba4052/src/serac/physics/solid_functional.hpp#L365-L375

UPDATE: OK, now I see the first potential issue is not a bug. The Piola transformation is not modifying the stress, it's being attached to the stress to modify the shape function gradient (from the original reference configuration to the perturbed one) when it finally encounters it in the residual integral (in the machinery of `functional` at a higher level in the call stack). Sorry, I think this is the second time I've made this mistake. On the other hand, I think that lends support to the proposal to move the shape sensitivity modifications to functional.

Second issue is here:
https://github.com/LLNL/serac/blob/7cf216a1be68719dc997f393d741070f1dba4052/src/serac/physics/solid_functional.hpp#L383
 
There should be a `det(I + dp_dX)` factor on the first item of the tuple, just as there is on the second (which is applied on 375). I think this bug may have escaped notice because we don't have dynamic shape optimization yet.

Both of these lead me to a suggestion:
I think we should consider moving the shape sensitivity modifications into the integration and interpolation operations of `functional`. We could update the nodal coordinates instead of carrying the shape displacement `p` around, and make the shape function gradients dual numbers to catch the sensitivities to the coordinates.

**Comment by samuelpmishLLNL** [comment]
I'm bumping into a related issue with the boundary integrals, since the derivatives terms for boundary integrals are w.r.t. isoparametric coordinates (so dp_dX, which should be named dp_dxi, is rectangular instead of square), so some of these calculations need to be reworked:

https://github.com/LLNL/serac/blob/7cf216a1be68719dc997f393d741070f1dba4052/src/serac/physics/solid_functional.hpp#L476-L503

The solution to this problem is less clear, since mfem doesn't provide $\displaystyle \frac{\partial X}{\partial \xi}$ in GetFaceGeometricFactors (despite having a flag that appears to let you ask for it), which I believe is necessary to compute the quantities we want.

**Comment by btalamini** [comment]
Yes, we need $\dfrac{\partial X}{\partial \xi}$. We should keep asking mfem to implement it. In theory, we could the factors we need by setting up a single element with the same nodal positions as the parent element, and asking for the derivatives of the shape functions. Could we set up this calculation somewhere under the hood and store the matrix?

**Comment by samuelpmishLLNL** [comment]
That's my current plan, to just implement these calculations in serac. I believe we requested that they fix that bug in GetFaceGeometricFactors over year ago, but it appears no progress has been made.

I think I'm going to try and get the batched shape function PR in first, and then do the "GeometricFactor" replacement kernels immediately afterward

**Comment by jamiebramwell** [comment]
I don't think (1) is a bug and I'm writing a test to confirm this. However, my math on this could very easily be wrong.

(2) and the boundary integrals are definitely wrong though.

**Comment by jamiebramwell** [comment]
Yeah, I added an option for the `serac_solid_functional_shape` test to turn off geometric nonlinearities, and I'm getting errors like this when I put in the suggested change:

```
The difference between shape_displacement[i] and pure_displacement[i] is 0.73318069851008805, which exceeds 1.0e-11, where
shape_displacement[i] evaluates to -0.22885312500001798,
pure_displacement[i] evaluates to -0.96203382351010602, and
1.0e-11 evaluates to 9.9999999999999994e-12.
```

The difference is about 5.0e-11 with the original code.

**Comment by jamiebramwell** [comment]
That said, I agree it would be way less error prone to include the shape calculations within `Functional` itself.

**Comment by btalamini** [comment]
Satisfied that current implmentation is correct. Refactoring is underway to spare the user from change-of-variable transformations in QOIs.
