### ISSUE TITLE
Cannot prescribe multiple components as Dirichlet boundary conditions when not fixing all components

### ISSUE THREAD

**Issue by barreracruz** [LLNL/serac#843]
The `setDisplacementBCs` method allows for setting only one component per boundary attribute. At the moment, there is no way to, for example, prescribe a displacement of zero in both X and Y directions in a 3D problem. If I try to do so, I get the following warning: 
***********************************
[WARNING in line 25 of file /g/g90/barrera/codes/serac-updatedLiqCrystElast/src/serac/physics/boundary_conditions/boundary_condition_manager.cpp]
MESSAGE=Multiple definition of essential boundary! Using first definition given.
***********************************

**Comment by jamiebramwell** [comment]
I believe this works now. @barreracruz , have you tried this recently?

**Comment by barreracruz** [comment]
Yes, it works now. Sorry for the late reply. Was on work travel last week.
