### ISSUE TITLE
build issues with axom + LTO (GCC12)

### ISSUE THREAD

**Issue by samuelpmishLLNL** [LLNL/serac#848]
the recent version of mpich for ubuntu 22.04 adds some link-time optimization flags to MPI targets, so all of the TPLs built end up with fat binaries. Enabling LTO flags also seems to mean that the libraries we depend on are not entirely black boxes any more, so when I compile serac, it complains about a bunch of warnings/errors in our libraries:

```
axom/sol.hpp:10487:31: error: potential null pointer dereference [-Werror=null-dereference]
[build] 10487 |                         *pref = obj;

axom/sidre/spio/IOBaton.cpp:119:28: error: ‘baton’ may be used uninitialized [-Werror=maybe-uninitialized]
[build]   119 |     int mpi_err = MPI_Ssend(&baton, 1, MPI_INT, m_rank_after_me, 0, m_mpi_comm);

axom/sidre/core/Attribute.hpp:57:39: error: potential null pointer dereference [-Werror=null-dereference]
[build]    57 |   IndexType getIndex() const { return m_index; }

...

```

and also one warning (promoted to error) in the stdlib:

```
/usr/include/c++/12/bits/hashtable_policy.h:277:57: error: potential null pointer dereference [-Werror=null-dereference]
[build]   277 |     _Hash_node_base(_Hash_node_base* __next) noexcept : _M_nxt(__next) { }
```

I'd like to just disable LTO entirely (for more than just the reasons above), but it's not clear to me how to do that to our uberenv/spack TPL system.

**Comment by white238** [comment]
Is this in the codevelop build or the regular one?

**Comment by samuelpmishLLNL** [comment]
with SERAC_ENABLE_CODEVELOP off, CMAKE_BUILD_TYPE=Debug I get:

```
[build]     inlined from ‘destroyAttribute’ at /home/sam/code/serac_libs_gcc12/builds/spack-stage-axom-0.6.1.6-wuzskwctqmcfbjkcowbj3f3xclajenzh/spack-src/src/axom/sidre/core/DataStore.cpp:427:19,
[build]     inlined from ‘destroyAttribute’ at /home/sam/code/serac_libs_gcc12/builds/spack-stage-axom-0.6.1.6-wuzskwctqmcfbjkcowbj3f3xclajenzh/spack-src/src/axom/sidre/core/DataStore.cpp:397:19:
[build] /home/sam/code/serac_libs_gcc12/builds/spack-stage-axom-0.6.1.6-wuzskwctqmcfbjkcowbj3f3xclajenzh/spack-src/src/axom/sidre/core/Attribute.hpp:57:39: error: potential null pointer dereference [-Werror=null-dereference]
[build]    57 |   IndexType getIndex() const { return m_index; }
[build]       |                                       ^
[build] lto1: all warnings being treated as errors
[build] make: *** [/tmp/ccGZwRgO.mk:18: tests/odes.ltrans8.ltrans.o] Error 1
[build] make: *** Waiting for unfinished jobs....
[build] lto-wrapper: fatal error: make returned 2 exit status
[build] compilation terminated.
[build] /usr/bin/ld: error: lto-wrapper failed
```

---------------------------

with SERAC_ENABLE_CODEVELOP off, CMAKE_BUILD_TYPE=Release I get:

```
[build]     inlined from ‘serac::BoundaryCondition::vectorCoefficient()’ at /home/sam/code/serac/src/serac/physics/boundary_conditions/boundary_condition.cpp:147:12:
[build] /usr/include/c++/12/bits/shared_ptr_base.h:1666:16: error: potential null pointer dereference [-Werror=null-dereference]
[build]  1666 |       { return _M_ptr; }
```
which is looks like it's probably just an undiagnosed code smell in our repo ([the affected code](https://github.com/LLNL/serac/blob/0aa56f4abf4e9370f8cb3317c4f33c7a277c3ce6/src/serac/physics/boundary_conditions/boundary_condition.cpp#L142-L148) is only ever used in the legacy stuff, so it's probably okay to delete). 

-------------------------------

with SERAC_ENABLE_CODEVELOP on, CMAKE_BUILD_TYPE=Debug serac has a lot of linker errors:

```
/usr/bin/ld: tests/axom_smoketest.ltrans0.ltrans.o:(.debug_info+0x34): undefined reference to `axom_smoketest.cpp.d8ff9011'
/usr/bin/ld: tests/mfem_array_std_algo.ltrans0.ltrans.o:(.debug_info+0x4f): undefined reference to `mfem_array_std_algo.cpp.32638c76'
/usr/bin/ld: /home/sam/code/serac/mfem/general/device.cpp:173: undefined reference to `mfem::Device::Get()'
...
```

-------------


with SERAC_ENABLE_CODEVELOP on, CMAKE_BUILD_TYPE=Release serac crashes the linker:

```
[build] during IPA pass: icf
[build] lto1: internal compiler error: Segmentation fault
[build] 0xb1f113 crash_signal
```

There's an issue on the [gcc bug tracker](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102067) about something that sounds very familiar, and was thought to be fixed with GCC-11. I responded to the discussion-- we'll see if anyone responds with helpful feedback. Interestingly, the original author of the issue was Matt [Godbolt](https://godbolt.org/).

-------------------

**Comment by samuelpmishLLNL** [comment]
A good suggestion from [the mpich developers](https://github.com/pmodels/mpich/issues/6271) has helped work around the crashing compiler issues on the release builds.

There are still issues with serac not building successfully with gcc-12, due to its better static analysis finding a few potential issues (e.g. the potential null dereference error above).
