### ISSUE TITLE
Document style guide

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#86]
Write a minimal "style guide" that will probably be amendments to the Google C++ style guide located [here](https://google.github.io/styleguide/cppguide.html).

**Comment by white238** [comment]
Axom's are here: https://axom.readthedocs.io/en/develop/docs/sphinx/coding_guide/index.html

It's been a while since I read them in depth and coding guidelines kind of evolve so I can't remember how much is super relevant.
