### ISSUE TITLE
Generating code check targets is slow

### ISSUE THREAD

**Issue by white238** [LLNL/serac#904]
@barreracruz reported that our CMake is getting hung up right after `Serac code checks: On`.

I have a suspicion that this loop is the culprit and could be optimized:

https://github.com/LLNL/serac/blob/fbd869f65dcc0660aa4c4048a9e65a98391fde0b/cmake/SeracMacros.cmake#L34-L64

My guess is it looping over too many files given the codevelop submodules and test directories.

Ideas: make original file globbing more specific with the includes and/or use this:

https://cmake.org/cmake/help/latest/command/list.html#filter

**Comment by jamiebramwell** [comment]
@white238 I believe this was resolved?

**Comment by white238** [comment]
Fixed in #945
