### ISSUE TITLE
Audit the memory management strategy of the solver class

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#91]
Now that a few solvers (including a composite solver) exist, a reexamination of the memory management strategies used for each object may be useful.

**Comment by joshessman-llnl** [comment]
In particular, it may be useful to see where `std::shared_ptr` can be replaced with `std::unique_ptr` to better convey ownership, and also to identify things that do not require any dynamic allocation.  

`std::weak_ptr` may be useful for expressing non-owning references to "simple" solver states that composite solvers would store.

**Comment by jamiebramwell** [comment]
Yep. I think a bunch of my `shared_ptr`s (particularly coefficients that the drivers create) can and should be `unique_ptr`s that we pass off to the solver using `std::move`. However, we may still need shared ownership in multiphysics cases, so a deeper investigation is needed.
