### ISSUE TITLE
Sundials is no longer optional

### ISSUE THREAD

**Issue by white238** [LLNL/serac#934]
If this was a mistake, Sundials should be guarded in the code. If it was not, the spack package variant should be removed.

**Comment by chapman39** [comment]
Related to this: if ~sundials+cuda, it may cause issues here, since the `when=` part doesn't check if the package is enabled. https://github.com/LLNL/serac/blob/develop/scripts/spack/packages/serac/package.py#L224

```python
    cuda_deps = ["axom", "mfem", "raja", "sundials", "umpire"]
    for dep in cuda_deps:
        depends_on("{0}+cuda".format(dep), when="+cuda")
        for sm_ in CudaPackage.cuda_arch_values:
            depends_on("{0} cuda_arch={1}".format(dep, sm_),
                    when="cuda_arch={0}".format(sm_))
```

edit: this has been resolved
