### ISSUE TITLE
Audit const correctness

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#95]
I am sure in my rush to get initial functionality out, I missed some things which could (and should) be marked `const`.

**Comment by joshessman-llnl** [comment]
I've been using a fairly loose definition of memory management on my branch for #91, so I've been indirectly addressing this when I run into missing `const`s

e.g. [this commit](https://github.com/LLNL/serac/commit/4a36e26b50c2d9ec1b76925037de9a9f099f2d4f)

**Comment by joshessman-llnl** [comment]
Mostly fixed by PR #105
