### ISSUE TITLE
code style requirement and updating clang-format

### ISSUE THREAD

**Issue by samuelpmishLLNL** [LLNL/serac#955]
the way we're currently enforcing code style is causing some impediments:

1. we don't merge PRs that don't conform to the style guide
2. we require a specific, older version of clang-format. This version isn't readily available in package managers (`apt` on ubuntu, `brew` on mac), official LLVM projects aren't distributing the binaries, and the CMake build of LLVM10 seems to be broken (and is unlikely to be fixed).
3. the CI machines do have the correct older version of the clang-format
4. We don't have a way to use the CI machines to apply the style changes

Some possible changes:
- Relax the style guide as a hard requirement. Minor style transgressions are easily addressed by applying `clang-format` anyway.
- Choose a more up-to-date version of clang-format. At present, it's not trivial to get a copy of the version we support.
- Introduce a way for the CI tools to apply style changes, so developers don't have to worry about locally applying the style guide. For example, we used to have a way for official serac developers to trigger actions/jobs by commenting "LGTM" on a PR. We could do something similar where a "make style" comment by a serac developer applies the style guide to the branch and commits the changes.

**Comment by white238** [comment]
The plan is to move clang-format forward very soon. I agree its painful to use now that clang-format10 cannot be apt-get.

**Comment by samuelpmishLLNL** [comment]
Could we consider adopting a regular update schedule for some of these things, e.g. update compilers/gtest/clang-format once a year?
