### ISSUE TITLE
New `CachedCMakePackage` changes cannot be overwritten

### ISSUE THREAD

**Issue by white238** [LLNL/serac#963]
One change in the Spack class `CachedCMakePackage` has larger bleeding than we thought. This needs to be fixed in Spack but I don't want to lose track of this issue.

Spack now adds this to the generated host-config:

```
set(CMAKE_GENERATOR "Unix Makefiles" CACHE STRING "")
```

The idea was that this could just be a default and would be overridden on the command line but that doesn't seem to be the case.

```
/Users/mish2/local/bin/cmake 
  -C /Users/mish2/code/serac/.vscode/serac_libs_july_23.cmake 
  -S/Users/mish2/code/serac -B/Users/mish2/code/serac/build 
  -G Ninja
```

```
loading initial cache file /Users/mish2/code/serac/.vscode/serac_libs_july_23.cmake
CMake Error: Error: generator : Ninja
Does not match the generator used previously: Unix Makefiles
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
```

**Comment by samuelpmishLLNL** [comment]
What's the status of this issue? The spack discussion made it sound like it was a solved problem, but our TPL build with spack seems to still emit .cmake files with the hardcoded generator specification.

**Comment by white238** [comment]
Pretty sure all we need to do is update our Spack commit sha

**Comment by white238** [comment]
Fixed in Spack PR something... I've confirmed it's no longer in our host-configs.
