### ISSUE TITLE
Investigate C++ linting tools

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#98]
Let's try to find a code check tool that can handle context-aware C++ style checking. [cpplint](https://github.com/cpplint/cpplint) is a possibility.

**Comment by jamiebramwell** [comment]
[clang-tidy](https://clang.llvm.org/extra/clang-tidy/) is another good option.

**Comment by joshessman-llnl** [comment]
clang-tidy is hopefully on its way into BLT: https://github.com/LLNL/blt/pull/395
