### ISSUE TITLE
Upgrade to C++17

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#99]
Upgrade the standard used to c++17. Compatibility with CUDA and BLT as well as compilers on ATS LC systems (like Sierra) needs to be investigated.

**Comment by joshessman-llnl** [comment]
The clang 4.0.0 CI version appears to not be plug-and-play with C++17, per the [logs](https://dev.azure.com/llnl-serac/serac/_build/results?buildId=434&view=logs&j=ee5e116a-579b-5a02-f53f-47b9bf970bfe&t=768a03e3-8edf-5f95-65fc-a159c8edc275&l=308).  This may be in BLT's scope, as Clang 4 requires `-std=c++1z` as opposed to `-std=c++17` (which is what GCC 8 uses).

**Comment by joshessman-llnl** [comment]
`nvcc` version 11 or higher is required per [the Nvidia website](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#cpp17-language-features).

**Comment by white238** [comment]
clang@4.0.0 should be dropped.

**Comment by jamiebramwell** [comment]
It looks like the [axom-maintained docker compiler containers](https://hub.docker.com/r/axom/compilers/tags) have newer versions now, so I fully support updating our clang version.

**Comment by jamiebramwell** [comment]
"now" - looks like they have for a while and I was just lazy.
